// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pokemon.sql

package database

import (
	"context"
	"database/sql"
)

const fetchPokemonDataById = `-- name: FetchPokemonDataById :one
SELECT id, name, type_1, type_2, hp, attack, defense, special_attack, special_defense, speed FROM pokedex WHERE id = $1
`

func (q *Queries) FetchPokemonDataById(ctx context.Context, id int32) (Pokedex, error) {
	row := q.db.QueryRowContext(ctx, fetchPokemonDataById, id)
	var i Pokedex
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type1,
		&i.Type2,
		&i.Hp,
		&i.Attack,
		&i.Defense,
		&i.SpecialAttack,
		&i.SpecialDefense,
		&i.Speed,
	)
	return i, err
}

const fetchPokemonDataByName = `-- name: FetchPokemonDataByName :one
SELECT id, name, type_1, type_2, hp, attack, defense, special_attack, special_defense, speed FROM pokedex WHERE LOWER(name) = LOWER($1)
`

func (q *Queries) FetchPokemonDataByName(ctx context.Context, lower string) (Pokedex, error) {
	row := q.db.QueryRowContext(ctx, fetchPokemonDataByName, lower)
	var i Pokedex
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type1,
		&i.Type2,
		&i.Hp,
		&i.Attack,
		&i.Defense,
		&i.SpecialAttack,
		&i.SpecialDefense,
		&i.Speed,
	)
	return i, err
}

const insertPokedex = `-- name: InsertPokedex :exec
INSERT INTO pokedex (
    id, name, type_1, type_2, hp, attack, defense, special_attack, special_defense, speed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type InsertPokedexParams struct {
	ID             int32
	Name           string
	Type1          string
	Type2          sql.NullString
	Hp             int32
	Attack         int32
	Defense        int32
	SpecialAttack  int32
	SpecialDefense int32
	Speed          int32
}

func (q *Queries) InsertPokedex(ctx context.Context, arg InsertPokedexParams) error {
	_, err := q.db.ExecContext(ctx, insertPokedex,
		arg.ID,
		arg.Name,
		arg.Type1,
		arg.Type2,
		arg.Hp,
		arg.Attack,
		arg.Defense,
		arg.SpecialAttack,
		arg.SpecialDefense,
		arg.Speed,
	)
	return err
}
